# Generated by Django 6.0.3 on 2026-04-20 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_cartitem'),
        ('orders', '0004_userprofile_address_userprofile_age_and_more'),
    ]

    operations = [
    ]
